parameters:
#    sopinet_template_landing.example.class: Sopinet\Template\LandingBundle\Example

services:
#    sopinet_template_landing.example:
#        class: %sopinet_template_landing.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
